Pisano
=====================

First Scenario
------------
* NAVIGATE TO PISANO
* CLICK ON IFRAME
* CHOOSE RECOMMENDATION LEVEL
* CHOOSE SENTIMENT LEVEL
* CLICK TO NEXT PAGE BUTTON
* ACCEPT THE AGGREMENT
* CHOOSE PISANO AS FAVORITE
* CLICK TO NEXT PAGE BUTTON ON SECOND PAGE
* TYPE RANDOM GENERATED EMAIL,NAME AND PHONENUMBER
* CLICK TO SUBMIT
* VERIFY THAT TEST WERE SUCCEEDED


Second Scenario
-----------
* NAVIGATE TO PISANO
* CLICK ON IFRAME
* CHOOSE RECOMMENDATION LEVEL
* CHOOSE SENTIMENT LEVEL
* CLICK TO NEXT PAGE BUTTON
* DON'T ACCEPT THE AGGREMENT
* CHOOSE PISANO AS FAVORITE
* CLICK TO NEXT PAGE BUTTON ON SECOND PAGE
* VALIDATE THAT YOU KICKED BACK TO FIRST PAGE